title: Conrad Li
subtitle: Bowdoin CS Student
description: 
favicon: 

about: 
  "I am a senior majoring in Computer Science and minoring in Economics at Bowdoin College. For summer 2020, I am interning as a Global Technology Analyst at Bank of America. I am interested in finding ways to incorporate technology into people's lives to bring about social good. You can reach me at zhikangli@hotmail.com. I'd love to chat!
  <br><br>
  Here is another section about me."


defaults:
  -
    scope:
      path: "/_posts/"
    values:
      layout: "post"

collections:
  pages:
    output: true
    permalink: /:title/
  
  posts:
    output: true
    permalink: /blog/:title/
    category: /blog/


  photography:
    output: true
    permalink: /photography/:title/
    category: /photography/
  
  portfolio:
    output: true
    permalink: /portfolio/:title/
    category: /portfolio/


# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Blog
    link: /blog/
    icon: ""
    
  - text: Portfolio
    link: /portfolio/
    icon: ""
  
  - text: Photography
    link: /photography/
    icon: ""

  - text: Resume
    link: /resume/
    icon: ""

  - text: Contact
    link: /contact/
    icon: ""
  



# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/conrad-li/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/conradli
    icon: fab fa-github-square


# plugin 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# sass 
sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown


###########################
##### Resume settings #####
###########################
resume_avatar:                  "true"
resume_name:                    "Conrad Li"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "zhikangli@hotmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "638 Smith Union, Brunswick, ME 04011"

resume_header_contact_info:     "638 Smith Union, Brunswick, ME 04011 • zhikangli@hotmail.com"
display_header_contact_info:    "false"





# Display resume sections
resume_section_education:       true
resume_section_skills:          true
resume_section_experience:      true
resume_section_projects:        true
resume_section_associations:    true
resume_section_interests:       true
resume_section_recognition:     false
resume_section_links:           false



# Resume social links
resume_social_links:
  resume_github_url:             "https://github.com/conradli"
  #resume_twitter_url:           
  #resume_dribbble_url:          
  #resume_facebook_url:         
  resume_linkedin_url:           "https://www.linkedin.com/in/conrad-li/"
  #resume_instagram_url:         
  resume_website_url:            "https://conradli.github.io/conradli"
  #resume_medium_url:
resume_print_social_links:       true
